#!/bin/sh

for dir in lib/ANNClassify
do
  cd $dir && ./bootstrap && cd -
done

libtoolize --automake --force --copy \
&& aclocal -I config \
&& autoheader \
&& automake --gnu --add-missing --copy \
&& autoconf

if test `basename ${0}` = "bootstrap-and-dist" ; then
        ./configure 
        make dist-bzip2
fi

