#!/bin/bash

REAL_PATH=`readlink -f $0`
TRACKING_HOME="$( cd "$( dirname "$REAL_PATH" )" && pwd )"
export TRACKING_HOME=${TRACKING_HOME%/bin}

export LD_LIBRARY_PATH=@sub_BOOST_LDPATH@:$TRACKING_HOME/lib:$LD_LIBRARY_PATH

perl $TRACKING_HOME/bin/tracking.pl $*

